"""Compose evidence-first Markdown and integration metadata for the offline site."""
from pathlib import Path
import json,hashlib,shutil,sys
ROOT=Path(__file__).resolve().parent.parent;OUT=ROOT/'output/simulations/ch02';SRC=ROOT/'simulations/ch02'
def read(n):return json.loads((OUT/n).read_text())
lr=read('linear_results.json');mr=read('mos_results.json');tr=read('transient_results.json');pz=read('pz_results.json');op=read('mos_operating_points.json');sel=read('gmid_selection.json')
mods=json.loads((ROOT/'output/derivations/ch02/modules.json').read_text());mnames={m['id']:m['title'] for m in mods};group={m['id']:{'title':m['title'],'linear':[],'mos':[],'pz':[],'transient':[]} for m in mods if m['id']!='00-conventions'}
for rows,key in [(lr,'linear'),(mr,'mos'),(pz,'pz'),(tr,'transient')]:
 for r in rows:group[r['module']][key].append(r)
assert all(any(g[k] for k in ['linear','mos','pz','transient']) for g in group.values())
thresholds={'ac_max_pointwise_complex_relative_error':2e-5,'pz_relative_root_error':2e-5,'transient_max_absolute_normalized_output_error':2e-5,'MOS_region':'region==2 and abs(Vds)>abs(Vdsat)'}
records=[]
for f in sorted((OUT/'runs').glob('*/result.json')):
 r=json.loads(f.read_text());deck=ROOT/r['deck'];log=f.parent/'spectre.out';summary={'name':f.parent.name,'ok':r['ok'],'returncode':r['metadata'].get('returncode'),'deck':r['deck'],'deck_sha256':r['sha256'],'spectre_log':str(log.relative_to(OUT)),'metadata':str(f.relative_to(OUT))};assert hashlib.sha256(deck.read_bytes()).hexdigest()==r['sha256'];records.append(summary)
checks=lr+mr+tr+pz;status='passed' if all(x['passed'] for x in checks) and all(r['ok'] and r['returncode']==0 for r in records) else 'failed'
report={'status':status,'simulator':'Cadence Spectre 18.1.0.077','bridge_version':'0.8.0','bridge_commit':'74649fbc28af14f1a6853ae8586b43cdba3747a1','source_book':'Analog Design Essentials (Willy Sansen).pdf','scope':'Representative models across 20 derivation groups, not every original slide circuit. Explicit-element linear simulation plus educational MOS1 transistor validation; no foundry PDK or layout parasitics.','linear_ac_tests':len(lr),'mos_ac_tests':len(mr),'pz_tests':len(pz),'transient_tests':len(tr),'total_checks':len(checks),'groups':len(group),'MOS_devices':len(op),'thresholds':thresholds,'max_linear_ac_error':max(x['max_relative_complex_error'] for x in lr),'max_mos_ac_error':max(x['max_relative_complex_error'] for x in mr),'max_pz_error':max(max(x['max_relative_pole_error'],x['max_relative_zero_error']) for x in pz),'max_transient_error':max(x['max_absolute_error'] for x in tr),'all_MOS_saturation_passed':all(x['saturation_passed'] for x in op.values()),'runs':records,'theory_source_hashes':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in (ROOT/'derivations/ch02').glob('*.md')}}
(OUT/'verification.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
shutil.copytree(SRC/'netlists',OUT/'netlists',dirs_exist_ok=True)
# No credentials or bridge.env are copied to the user-facing website directory.
summary={}
for mid,g in group.items():
 ids=[r['id'] for k in ['linear','mos','pz','transient'] for r in g[k]]
 summary[mid]={'status':'representative_models_verified','title':g['title'],'case_ids':ids,'linear_count':len(g['linear']),'mos_count':len(g['mos']),'pz_count':len(g['pz']),'transient_count':len(g['transient']),'scope_zh':'本推导组的代表模型已完成 Spectre 验证；覆盖范围以所列网表为准，未逐一搭建所有幻灯片电路。','html':'../../simulations/ch02/index.html#'+mid,'markdown':'../../simulations/ch02/report.md'}
(OUT/'module_summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2))
md=['# 第二章：Spectre 仿真与推导对照','','本轮使用远程 **Cadence Spectre 18.1.0.077** 实际运行网表，通过 `virtuoso-bridge-lite 0.8.0` 下载原始 PSF。涵盖 20 组推导的代表模型；以下清楚列出每个电路与检查，没有将它等同于逐一完成所有幻灯片电路。','','## 结果总览','','| 验证 | 数量 | 结果 |','|---|---:|---|',f'| 显式元件的小信号 AC | {len(lr)} | 全部通过 |',f'| gm/Id 法确定尺寸的 MOS1 电路 AC | {len(mr)} | 全部通过 |',f'| 直接极零分析 | {len(pz)} | 全部通过 |',f'| 极零对／基准瞬态 | {len(tr)} | 全部通过 |',f'| MOS 工作区 | {len(op)} 只 | 全部在饱和区 |','','比较完整式时，AC 与极零位置容许相对误差为 $2\\times10^{-5}$；瞬态容许归一化输出的绝对误差为 $2\\times10^{-5}$。线性 AC 最大误差约 $1.59\\times10^{-5}$，MOS AC 约 $4.69\\times10^{-6}$，极零位置约 $1.93\\times10^{-6}$。原始 PSF 有输出有效位数限制。','','[完整验证记录](verification.json) · [gm/Id 选点与尺寸](gmid_selection.json) · [MOS 工作点](mos_operating_points.json)','','## 模型与仿真层级','','1. **线性元件模型**：使用真正的 Spectre resistor、capacitor、inductor、vccs、vcvs 创建连接。KCL 闭式公式另由 Python 计算，不把完整 H(s) 塞进单个行为源再称作电路验证。增益增强的辅助极点用实际 R/C 实现。','2. **晶体管模型**：使用明列常数的 MOS1 教学模型，从 DC 扫描取得 gm/Id 与电流密度，选工作点与尺寸，再用 Spectre 求 DC／AC。','3. **结果比对**：MOS 仿真保留其本征 Cgs；把实际工作点的 gm、gds、电容代入相应完整小信号式。另列教材简式的近似偏差，不把近似失效混成仿真失败。','','没有指定晶圆厂 PDK，因此本轮不作工艺、工艺角、蒙特卡洛 或版图寄生验证。线性 AC 扫至 1 THz、MOS AC 扫至 10 GHz，是检查指定数学模型的极限；这些上限不代表长沟道 MOS 实际可用带宽。','','## gm/Id：先扫描，再选工作点与尺寸','','NMOS／PMOS 各以 $W=20$ µm、$L=2$ µm、$|V_{DS}|=1$ V，扫描 $V_{OV}=0.05$–$0.60$ V，步长 5 mV。教学模型采 $|V_T|=0.45$ V、$KP=100$ µA/V²、$\\lambda=0.1$ V⁻¹、$\\gamma=0$、$t_{ox}=10$ nm。其余参数与引脚 D/G/S/B 顺序保存在网表。','','![gm/Id 查表](assets/gmid_lookup.svg)','','从仿真曲线选 $g_m/I_D=10$ V⁻¹，对应 $V_{OV}=0.2$ V；沿用 029 的 $GBW=100$ MHz、$C_L=3$ pF：','','$$g_{m,\\mathrm{target}}=2\\pi(100\\,\\mathrm{MHz})(3\\,\\mathrm{pF})=1.88496\\,\\mathrm{mS}.$$','','$$I_{D,\\mathrm{target}}=g_{m,\\mathrm{target}}/(g_m/I_D)=188.496\\,\\mu\\mathrm A.$$','','$$W=\\frac{I_{D,\\mathrm{target}}}{I_{D,\\mathrm{lookup}}/W_{\\mathrm{lookup}}}=171.360\\,\\mu\\mathrm m,\\qquad L=2\\,\\mu\\mathrm m.$$','','教材忽略沟道长度调制的尺寸式给 $W=188.496$ µm；本次 MOS1 电流含 $(1+\\lambda V_{DS})=1.1$，因此查表选出的 W 较小。这是可解释的模型差异，没有直接把教材尺寸当成 PDK 尺寸。','','[MOS1 查表网表](netlists/gmid_characterization.scs) · [完整查表 CSV](csv/gmid_lookup.csv) · [七个 MOS 电路网表](netlists/mos_validation.scs)','','## 直接极零分析','','使用 Spectre `pz`，并设 `docancel=no`，因此可以看到相消前重叠的极点与零点。PSF 中的位置单位是 Hz；与理论根 $s$ 比较前先除以 $2\\pi$。','','![直接极零分析](assets/pole_zero.svg)','','- 米勒右半平面零点约 **+636.620 MHz**。','- 两级米勒补偿右半平面零点约 **+212.207 MHz**。','- 跟随器相消案例在 **−13.2629 MHz** 有重叠极点／零点，剩余主极点约 **−4.18829 MHz**。','- 跟随器复极点案例得到共轭极点，与二次分母判别式一致。','','[极零解析值与理论值](pz_results.json)','','## 极零对与建立过程','','闭环由受控源、积分电容及一个 R/C 极点构成。输入为延迟 1 µs、上升时间 1 ns 的阶跃；理论参考对有限上升时间作了积分，避免把理想瞬时阶跃误差算给 Spectre。','','![极零对的 Spectre 瞬态](assets/doublet_transient.svg)','','单极点基准达到 0.1% 误差约需 **1.101 µs**；具有极零对引起的慢尾响应的案例约需 **184.641 µs**。另有一个慢速留数为负的案例呈现过冲，约 **30.741 µs** 进入 0.1% 范围。建立时间依下载波形的最后超差点估算，其时间分辨率受保存样点限制。','','[瞬态网表](netlists/doublet_transient.scs) · [瞬态验证数值](transient_results.json)','','## 逐组电路、波形与近似差异','']
for mid,g in group.items():
 md += [f'<a id="{mid}"></a>',f'### {mid[:2]} · {g["title"]}','',summary[mid]['scope_zh'],'',f'[完整公式推导](../../derivations/ch02/{mid}.html)','']
 for key,label in [('linear','显式小信号组件'),('mos','MOS1 教学晶体管')]:
  for r in g[key]:
   md += [f'#### {r["id"]} · {label}','','由 Spectre 输出的复数波形，逐频点与完整式比较；相位与正负号均纳入。',f'最大相对误差：**{r["max_relative_complex_error"]:.3g}**；保存点数：{r["samples"]}。','']
   if key=='mos':md += [f'DC 输出：{r["dc_output_V"]:.6g} V；所有器件通过饱和区检查。完整式使用实际工作点的 gm、gds 与 Cgs。','']
   if r.get('approximation'):md += [f'教材近似式另行比较：在 1 Hz–1 MHz，最大相对偏差为 **{100*r["approximation"]["max_relative_error_up_to_1MHz"]:.3g}%**。此数字与完整式验证分开；橙色虚线显示近似式。','']
   md += [f'![{r["id"]} 仿真对照]({r["asset"]})','',f'[波形 CSV]({r["csv"]}) · [运行网表](netlists/{"mos_validation" if key=="mos" else "linear_suite"}.scs)','']
 if g['pz']:md += ['本组另有直接 PZ 结果：'+ '、'.join(r['id'] for r in g['pz'])+'。详见上方极零图与 JSON。','']
 if g['transient']:md += ['本组的三个瞬态情境及波形见上方极零对小节。','']
md += ['## 尚待延伸的验证','','- 以实际 PDK 替换 MOS1，重新产生 gm/Id、电容和增益查表。','- 本轮针对各推导组的代表模型；例如 0216 的线性区可调 M2、0246–0247 的完整有源电感实现，仍需各自的器件级偏置与稳定性案例。','- BJT 目前使用显式 混合 π 型 等效元件；未使用工艺 BJT 模型扫描偏置。','- 0244 的教材原模型／符号仍待厘清；仿真验证了本项目明列的等效模型，不能反向证明该教材原式。','','## 重现与原始数据','','所有正式网表、CSV、图及原始 PSF 都保存在本地工作区。远程 `/tmp` 只用作运行暂存；不依赖其长期存在。运行命令、exit code 与网表 SHA-256 保存在各 run 的 `result.json`。','','[使用与重建说明](README.md) · [运行记录索引](verification.json)']
(OUT/'report.md').write_text('\n'.join(md)+'\n')
print(f'{status}: {len(checks)} checks across {len(group)} representative derivation groups.')
